// examples/react-app/src/components/Counter.tsx
import { useDispatch } from '@ripple/react'
import { useCounterCount } from '../hooks'
import { counterEvents } from '../store/events'

/**
 * Counter Component
 * Demonstrates simple synchronous state updates using factory subscription hooks
 */
export function Counter() {
  const dispatch = useDispatch()
  const count = useCounterCount()

  const handleIncrement = () => {
    dispatch(counterEvents.increment)
  }

  const handleDecrement = () => {
    dispatch(counterEvents.decrement)
  }

  const handleReset = () => {
    dispatch(counterEvents.reset)
  }

  const handleSet = () => {
    const value = prompt('Enter a number:')
    if (value !== null) {
      const numValue = parseInt(value, 10)
      if (!isNaN(numValue)) {
        dispatch(counterEvents.set, { value: numValue })
      }
    }
  }

  return (
    <div style={{ padding: '20px', border: '1px solid #ccc', borderRadius: '8px', margin: '10px' }}>
      <h2>Counter Example</h2>
      <p style={{ fontSize: '24px', fontWeight: 'bold' }}>Count: {count}</p>
      <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
        <button onClick={handleIncrement}>Increment</button>
        <button onClick={handleDecrement}>Decrement</button>
        <button onClick={handleReset}>Reset</button>
        <button onClick={handleSet}>Set Value</button>
      </div>
      <p style={{ fontSize: '12px', color: '#666', marginTop: '10px' }}>
        This demonstrates simple synchronous state updates using the Ripple Store.
      </p>
    </div>
  )
}

// examples/angular-app/src/app/components/counter/counter.component.ts
import { Component } from '@angular/core';
import { injectSubscription, injectDispatch } from '@ripple/angular';
import { counterEvents } from '../../../store/events';

/**
 * Counter Component
 * Demonstrates simple synchronous state updates
 */
@Component({
  selector: 'app-counter',
  standalone: true,
  template: `
    <div class="example-container">
      <h2>Counter Example</h2>
      <p class="count-display">Count: {{ count() }}</p>
      <div class="button-group">
        <button (click)="handleIncrement()">Increment</button>
        <button (click)="handleDecrement()">Decrement</button>
        <button (click)="handleReset()">Reset</button>
        <button (click)="handleSet()">Set Value</button>
      </div>
      <p class="description">
        This demonstrates simple synchronous state updates using the Ripple Store.
      </p>
    </div>
  `,
  styles: [`
    .example-container {
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 8px;
      margin: 10px;
      background: white;
    }

    h2 {
      margin-top: 0;
    }

    .count-display {
      font-size: 24px;
      font-weight: bold;
      margin: 20px 0;
    }

    .button-group {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      margin-bottom: 10px;
    }

    .description {
      font-size: 12px;
      color: #666;
      margin-top: 10px;
    }
  `]
})
export class CounterComponent {
  private dispatch = injectDispatch();

  // Use subscription instead of computed() - provides shared computation and better performance
  count = injectSubscription<number>('counter/count');

  handleIncrement() {
    this.dispatch(counterEvents.increment);
  }

  handleDecrement() {
    this.dispatch(counterEvents.decrement);
  }

  handleReset() {
    this.dispatch(counterEvents.reset);
  }

  handleSet() {
    const value = prompt('Enter a number:');
    if (value !== null) {
      const numValue = parseInt(value, 10);
      if (!isNaN(numValue)) {
        this.dispatch(counterEvents.set, { value: numValue });
      }
    }
  }
}
